name: Build and Release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64
          - os: macos-latest
            rid: osx-x64

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./MtsCli.Executor/MtsCli.Executor.csproj --configuration Release --no-build -p:PublishAot=true -p:PublishSingleFile=true --self-contained true -r ${{ matrix.rid }} -f net9.0 -o ./MtsCli.Executor/bin/Release/net9.0/${{ matrix.rid }}/publish/
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: mts-cli-${{ matrix.rid }}
        path: ./MtsCli.Executor/bin/Release/net9.0/${{ matrix.rid }}/publish/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4.1.7

      - name: Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          files: |
            mts-cli-win-x64/*
            mts-cli-linux-x64/*
            mts-cli-osx-x64/*

